In [1]:
import numpy as np
import pandas as pd

In [4]:
employees = pd.DataFrame({
    'Employee_ID':[1,2,3,4,5],
    'Name':['Raghav','Anjali','Pragya','Rahul','Aman'],
    'Department':['HR','IT','Finance','IT','HR']
})

Salaries = pd.DataFrame({
    'Employee_ID':[1,2,3,6,7],
    'Salary':[60000,80000,65000,70000,90000],
    'Bonus':[5000,10000,7000,8000,12000]
})

In [5]:
employees

   Employee_ID    Name Department
0            1  Raghav         HR
1            2  Anjali         IT
2            3  Pragya    Finance
3            4   Rahul         IT
4            5    Aman         HR

In [6]:
Salaries

   Employee_ID  Salary  Bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

### Merjing Two DataFrame

In [12]:
pd.merge(employees,Salaries,on='Employee_ID',how = 'inner')

   Employee_ID    Name Department  Salary  Bonus
0            1  Raghav         HR   60000   5000
1            2  Anjali         IT   80000  10000
2            3  Pragya    Finance   65000   7000

In [13]:
pd.merge(employees,Salaries,on='Employee_ID',how = 'outer')

   Employee_ID    Name Department   Salary    Bonus
0            1  Raghav         HR  60000.0   5000.0
1            2  Anjali         IT  80000.0  10000.0
2            3  Pragya    Finance  65000.0   7000.0
3            4   Rahul         IT      NaN      NaN
4            5    Aman         HR      NaN      NaN
5            6     NaN        NaN  70000.0   8000.0
6            7     NaN        NaN  90000.0  12000.0

In [16]:
pd.merge(employees,Salaries,on='Employee_ID',how = 'left')

   Employee_ID    Name Department   Salary    Bonus
0            1  Raghav         HR  60000.0   5000.0
1            2  Anjali         IT  80000.0  10000.0
2            3  Pragya    Finance  65000.0   7000.0
3            4   Rahul         IT      NaN      NaN
4            5    Aman         HR      NaN      NaN

In [17]:
pd.merge(employees,Salaries,on='Employee_ID',how = 'right')

   Employee_ID    Name Department  Salary  Bonus
0            1  Raghav         HR   60000   5000
1            2  Anjali         IT   80000  10000
2            3  Pragya    Finance   65000   7000
3            6     NaN        NaN   70000   8000
4            7     NaN        NaN   90000  12000

### Concatination of 2 dataframes

In [19]:
df1 = pd.DataFrame({
    'A':['A0','A1','A2'],
    'B':['B0','B1','B2'],
    'C':['C0','C1','C2']
})

df2 = pd.DataFrame({
    'A':['A3','A4','A5'],
    'B':['B3','B4','B5'],
    'C':['C3','C4','C5']
})

In [21]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [22]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [23]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [24]:
pd.concat([df1,df2],axis = 1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

### Joining 2 data framess

In [26]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [27]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [28]:
df2

   score
2     85
3     90
4     75

In [31]:
df1.join(df2,how = 'outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [32]:
df2.join(df1)

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN